revising  in Chinese version
noffle/art-of-readme pull request #37
Opened 2016-10-23 12:13 UTC by sept08

1. revised some blunt words.
2. Added unfinished translation.

2016-10-23 22:13 UTC, noffle commented
Thanks @sept08.

cc @qihaiyan @BrettDong

2016-10-25 00:59 UTC, qihaiyan commented
@Artoria2e5 is more professional, do you mind to give a review?

2016-10-25 01:25 UTC, Artoria2e5 requested changes
除了以上提到的先 rebase一下吧。

2016-10-25 01:25 UTC, Artoria2e5 commented on README-zh.md
> +value"`。有的是因为文档里只是一些代码片段。这使得模块使用者只能通过阅读源代码来理解模块是怎么工作的。编写优秀的文档可以使用户不用阅读源码就能理解你模块的精妙之处。
这个缩写其实没多大必要展开……

2016-10-25 01:25 UTC, Artoria2e5 commented on README-zh.md
> +有的读者<sup>[[1]](#footnote-1)</sup>开了个玩笑，认为“README”应该是来自于“爱丽丝漫游仙境”，一瓶药水和一个蛋糕上分别贴着 *"DRINK ME"* 和 *"EAT ME"* 的标签。
上标吼啊。

2016-10-25 01:25 UTC, Artoria2e5 commented on README-zh.md
> +## 专业模块探讨
原翻译在含义上更准一点，当然可能是得益于其机械感。

2016-10-25 01:25 UTC, Artoria2e5 commented on README-zh.md
> +## 扩展: 其它好的实践
叫做“拓展”的话似乎丢了一点语气……看看怎么搞出“买一送一”的感觉？（大雾）

2016-10-25 01:25 UTC, Artoria2e5 commented on README-zh.md
> +发现了错误? 存在某些无意义的东西? 想我发起一个[pull
`? ` → `？`

2016-10-25 01:25 UTC, Artoria2e5 commented on README-zh.md
> +## 扩展: 其它好的实践
`: `→`：`

2016-10-25 17:49 UTC, sept08 commented
1、我把“战斗的召唤”一栏按照原文位置调整，确定的确实bonus翻译为“奖励”更好一点。
2、补充了英文版10月21日加入的一些新内容的翻译。

2016-10-25 21:38 UTC, Artoria2e5 commented on README-zh.md
> +*   [https://github.com/feross/bittorrent-dht
..?

2016-10-25 21:38 UTC, Artoria2e5 approved these changes

2016-10-26 01:29 UTC, sept08 commented on README-zh.md
> +*   [https://github.com/feross/bittorrent-dht
i edit the markdown document with Atom. This trange wrap is done automatically by the editor, I also don't understand how it's going on, but the preview result had no effect.
我本地markdown文件是用Atom写的，装了linter-markdown包做语法检查，编辑这块编辑器自动换行的，我也不清楚这种奇葩的换行是什么鬼，不过preview效果却不影响。

2016-10-26 01:30 UTC, Artoria2e5 commented on README-zh.md
> +*   [https://github.com/feross/bittorrent-dht
This should be good then.

2016-10-26 01:59 UTC, noffle commented
Woohoo! Thank you @sept08 and @Artoria2e5 for your hard work! :star2:

2016-10-26 01:59 UTC, merged