Update README-de-DE.md
noffle/art-of-readme pull request #66
Opened 2021-04-09 09:28 UTC by chnuessli

fixed some typos in german. awesome article, thank you

2021-04-09 16:11 UTC, Ryuno-Ki requested changes
Danke!

Du scheinst einen schweizerischen Hintergrund zu haben, wo es kein ß (scharf-s, Dreierle-s) gibt.
Würde es sinnvoll erscheinen, dafür ein README-de-CH.md anzulegen?

Sofern das ß beibehalten wird, würde ich den PR approven.

---
Thanks!

Looks like you have a background in Switzerland, where they don't use ß.
Would it make sense to create a README-de-CH.md for this?

If you would keep the ß, I'm going to approve this PR.

// CC @noffle

2021-04-09 16:11 UTC, Ryuno-Ki commented on README-de-DE.md
> +in dein Werk. Der Nutzer erwartet, dass ein Modul seine Bedürfnisse erfüllt,
Es war mein Versuch, es inklusiver zu formulieren. (Ich sehe aber, wie du auf die Korrektur kommst)

2021-04-09 16:11 UTC, Ryuno-Ki commented on README-de-DE.md
> +also musst du genau erklären, was für ein Problem dein Modul löst und wie
Ups.

2021-04-09 16:11 UTC, Ryuno-Ki commented on README-de-DE.md
> +durchgelesen zu werden, um mehr von einer Gemeinschaft zu lernen, die durchwegs
`durchwegs` ist [umgangssprachlich](https://www.duden.de/rechtschreibung/durchwegs) für `durchweg` :)

2021-04-09 16:11 UTC, Ryuno-Ki commented on README-de-DE.md
> +5. Sei behutsam mit dem Nutzen von Abzeichen. Sie können leicht
Okay, `bedachtsam` ist wohl [gehobenes Deutsch](https://www.duden.de/rechtschreibung/bedachtsam).

2021-04-09 16:11 UTC, Ryuno-Ki commented on README-de-DE.md
> +   werden. Sie fügen visuelle Störungen zu deiner README hinzu und
Ups.

2021-04-09 16:11 UTC, Ryuno-Ki commented on README-de-DE.md
> +Dieses kleine Projekt begann damals im Mai in Berlin bei der squantconf, wo
Gotcha!

2021-04-10 06:37 UTC, chnuessli commented on README-de-DE.md
> +5. Sei behutsam mit dem Nutzen von Abzeichen. Sie können leicht
Das kann sein :)

2021-04-10 06:39 UTC, chnuessli commented
Hi @Ryuno-Ki.
Schweizer wohl war ;) aber ich sehe, du hast dir bei vielem sehr gute Gedanken gemacht, und du bist des hochdeutschen sicher mächtiger als ich. Ich habe im https://github.com/noffle/art-of-readme/pull/67 PR, eine CH Version gemacht und die S wieder zurückgesetzt. Um es sichtbarer zu machen, extra ein neuer PR.

2021-04-10 06:39 UTC, closed without merging

2021-04-10 12:49 UTC, Ryuno-Ki commented
@chnuessli Danke!
Nachdem dein PR dann akzeptiert worden ist, werde ich die Vorschläge aus diesem noch einmal einreichen und dich als Co-Author markieren.