insert swiss-german version, change the german S
noffle/art-of-readme pull request #67
Opened 2021-04-10 06:37 UTC by chnuessli

2021-04-10 13:23 UTC, Ryuno-Ki requested changes
Search and Replace would have been too easy.

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +[Spanisch](README-es-ES.md) und [Französisch](README-fr.md) gelesen werden.*
Perhaps you want to add a link to README-de-DE.md here?

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +Das Muster, das README komplett in Großbuchstaben erscheint, ist eine
```suggestion
Das Muster, das README komplett in Grossbuchstaben erscheint, ist eine
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +Dies ist ebenso für Konsumierende von Modulen geschrieben, da jeder Auto auch
```suggestion
Dies ist ebenso für Konsumierende von Modulen geschrieben, da jeder Autor auch
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +Node.js hat ein "großes" Ökosystem: Es besteht im Wesentlichen aus einer
```suggestion
Node.js hat ein "grosses" Ökosystem: Es besteht im Wesentlichen aus einer
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +## Alle Straßen führen zur README.md
```suggestion
## Alle Strassen führen zur README.md
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +wird schließlich deine README zu sehen bekommen. Da sich deine Nutzer
```suggestion
wird schliesslich deine README zu sehen bekommen. Da sich deine Nutzer
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +kannst, um ihren ersten Eindruck maximal effektiv zu mcahen?
```suggestion
kannst, um ihren ersten Eindruck maximal effektiv zu machen?
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +dein öffentlichkeitswirksames Maß deiner Arbeit.
```suggestion
dein öffentlichkeitswirksames Mass deiner Arbeit.
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +Es heißt, dass jene, die nicht aus ihrer Vergangenheit lernen, dazu verdammt
```suggestion
Es heisst, dass jene, die nicht aus ihrer Vergangenheit lernen, dazu verdammt
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +[Mönche der Perl-Community](http://perlmonks.org) der tatsächlich viel
```suggestion
[Mönche der Perl-Community](http://perlmonks.org) tatsächlich viel
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +   vielversprechend, auch wenn es annimmt, dass ich weiß, was "aabb" ist. Wenn
```suggestion
   vielversprechend, auch wenn es annimmt, dass ich weiss, was "aabb" ist. Wenn
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +   ausschließen, wenn die Lizenz mit deiner Arbeit unkompatibel ist. Generell
```suggestion
   ausschliessen, wenn die Lizenz mit deiner Arbeit unkompatibel ist. Generell
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +Du wirst außerdem anfangen, eine eigene persönliche Heuristik zu entwickeln,
```suggestion
Du wirst ausserdem anfangen, eine eigene persönliche Heuristik zu entwickeln,
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +Diese Denkweise spricht nicht jeden an; sie verlangt das eigene Ego außen vor
```suggestion
Diese Denkweise spricht nicht jeden an; sie verlangt das eigene Ego aussen vor
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +      **Benutzung** behandlet wurde.
```suggestion
      **Benutzung** behandelt wurde.
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +      [Fußnoten](https://daringfireball.net/projects/markdown/syntax#link) am
```suggestion
      [Fussnoten](https://daringfireball.net/projects/markdown/syntax#link) am
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +   in der `package.json` zu benutzen, um Modul-Höhlenforscher an deine Pfote zu
```suggestion
   in der `package.json` zu benutzen, um Modul-Höhlenforscher an deine Pforte zu
```
:dog:

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +## Fußnoten
```suggestion
## Fussnoten
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +   Die meisten Systeme heutzutage werden jedoch nicht Großbuchstaben vor
```suggestion
   Die meisten Systeme heutzutage werden jedoch nicht Grossbuchstaben vor
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +   auf die visuelle Hervorhebung durch die Nutzung der Großbuchstaben
```suggestion
   auf die visuelle Hervorhebung durch die Nutzung der Grossbuchstaben
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-CH.md
> +- [@randomC0der](https://github.com/randomC0der)
Füg hier gerne auch deinen Namen ein!

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Ein Leser<sup>[1](#footnote-1)</sup> schlug vor, daß der Title README eine
```suggestion
Ein Leser<sup>[1](#footnote-1)</sup> schlug vor, dass der Title README eine
```
Neue deutsche Rechtschreibung schreibt `dass` statt `daß` :-(

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Hervorhebung durch das Benutzen von Majuskeln, sondern auch dadurch, daß
```suggestion
Hervorhebung durch das Benutzen von Majuskeln, sondern auch dadurch, dass
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +gelesen sollte, bevor weitergemacht wird."* Laßt uns zusammen erkunden,
```suggestion
gelesen sollte, bevor weitergemacht wird."* Lasst uns zusammen erkunden,
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +ist, etwas zu schaffen, daß überdauert. Es ist eine inhärente Motivation,
```suggestion
ist, etwas zu schaffen, dass überdauert. Es ist eine inhärente Motivation,
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Monaten wird ein Modul ohne Dokumentation wie neu und unbekannt außehen.
```suggestion
Monaten wird ein Modul ohne Dokumentation wie neu und unbekannt aussehen.
```
aus|sehen

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Auch wenn es sich auf Node.js fokußiert, behauptet der Autor, daß die
```suggestion
Auch wenn es sich auf Node.js fokussiert, behauptet der Autor, dass die
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Lektionen sich genauso gut auf andere Programmierumgebungen anwenden laßen.
```suggestion
Lektionen sich genauso gut auf andere Programmierumgebungen anwenden lassen.
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +dazwischen. Es gibt sogar welche, von denen wir gar nicht wißen, was sie tun!
```suggestion
dazwischen. Es gibt sogar welche, von denen wir gar nicht wissen, was sie tun!
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Wo landen die Module, die eine Dokumentation haben, auf dem Qualitätßpektrum?
```suggestion
Wo landen die Module, die eine Dokumentation haben, auf dem Qualitätsspektrum?
```
Qualitäts|spektrum

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +beßer als gar nichts, aber sie tendieren dazu, in das Worst-Case Szenario
```suggestion
besser als gar nichts, aber sie tendieren dazu, in das Worst-Case Szenario
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +aus, daß der Nutzer aus dem Quellcode ferngehalten wird, indem die Anleitungen
```suggestion
aus, dass der Nutzer aus dem Quellcode ferngehalten wird, indem die Anleitungen
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Auffindbarkeits-Problem sind unendlich beßer als ein Kulturproblem, bei dem
```suggestion
Auffindbarkeits-Problem sind unendlich besser als ein Kulturproblem, bei dem
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Darüberhinaus läßt sich Auffindbarkeit -- wie wir herausfinden werden --
```suggestion
Darüberhinaus lässt sich Auffindbarkeit -- wie wir herausfinden werden --
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +einfacher adreßieren.
```suggestion
einfacher adressieren.
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Dies kann auch in Form von Rß-Feeds und Mailinglisten geschehen, die neue
```suggestion
Dies kann auch in Form von RSS-Feeds und Mailinglisten geschehen, die neue
```
:joy_cat:

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +## Profeßionelle Modul-Höhlenforschung
```suggestion
## Professionelle Modul-Höhlenforschung
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +in dein Werk. Der Nutzer erwartet, daß ein Modul ihre Bedürfniße erfüllt,
```suggestion
in dein Werk. Der Nutzer erwartet, dass ein Modul ihre Bedürfnisse erfüllt,
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +2. zu zeigen, wie es in Aktion außieht
```suggestion
2. zu zeigen, wie es in Aktion aussieht
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Dies ist *deine* Aufgabe. Es liegt an den Modulersteller zu beweisen, daß
```suggestion
Dies ist *deine* Aufgabe. Es liegt an den Modulersteller zu beweisen, dass
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Es heißt, daß jene, die nicht aus ihrer Vergangenheit lernen, dazu verdammt
```suggestion
Es heißt, dass jene, die nicht aus ihrer Vergangenheit lernen, dazu verdammt
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Es stellt sich heraus, daß die
```suggestion
Es stellt sich heraus, dass die
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +erworben haben. CPAN ist eine wundervolle Reßource, die es wert ist,
```suggestion
erworben haben. CPAN ist eine wundervolle Ressource, die es wert ist,
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Ohne README werden Entwickler den Quellcode betrachten müßen, um ihn zu
```suggestion
Ohne README werden Entwickler den Quellcode betrachten müssen, um ihn zu
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +> ohne jemals auf den Quellcode schauen zu müßen. Das ist sehr wichtig. Es
```suggestion
> ohne jemals auf den Quellcode schauen zu müssen. Das ist sehr wichtig. Es
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +> ermöglicht es dir, die dokumentierte Schnittstelle deines Moduls von deßen
```suggestion
> ermöglicht es dir, die dokumentierte Schnittstelle deines Moduls von dessen
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +> Implementierung zu trennen (gut). Das ist gut, weil es bedeutet, daß du
```suggestion
> Implementierung zu trennen (gut). Das ist gut, weil es bedeutet, dass du
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +### Schlüßelelemente
```suggestion
### Schlüsselelemente
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +um festzustellen, ob es die Bedürfniße des Entwicklers abdeckt. Im
```suggestion
um festzustellen, ob es die Bedürfnisse des Entwicklers abdeckt. Im
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Musterabgleichs, welches das Gehirn lösen muß, wobei jeder Schritt den
```suggestion
Musterabgleichs, welches das Gehirn lösen muss, wobei jeder Schritt den
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Entwickler tiefer in das Modul und deßen Details führt.
```suggestion
Entwickler tiefer in das Modul und dessen Details führt.
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   vielversprechend, auch wenn es annimmt, daß ich weiß, was "aabb" ist. Wenn
```suggestion
   vielversprechend, auch wenn es annimmt, dass ich weiß, was "aabb" ist. Wenn
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   `collide-2d-aabb-aabb` sagt, daß es
```suggestion
   `collide-2d-aabb-aabb` sagt, dass es
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   wie gut es in meinen Code paßen wird:
```suggestion
   wie gut es in meinen Code passen wird:
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   wäre es toll zu sehen, wie das Modul in Aktion außieht. Ich kann schnell
```suggestion
   wäre es toll zu sehen, wie das Modul in Aktion aussieht. Ich kann schnell
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   Promises/Callbacks und ES6 außehen sollten. Falls es den Vorstellungen
```suggestion
   Promises/Callbacks und ES6 aussehen sollten. Falls es den Vorstellungen
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   geneigt, das Modul zu benutzen. Ich muß nur noch das API überfliegen, um zu
```suggestion
   geneigt, das Modul zu benutzen. Ich muss nur noch das API überfliegen, um zu
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   meine Codebase integrieren. Der Abschnitt zum API muß daher die Objekte und
```suggestion
   meine Codebase integrieren. Der Abschnitt zum API muss daher die Objekte und
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +5. *Installation* -- wenn ich bis hierhin gelesen habe, bin ich bereit, daß
```suggestion
5. *Installation* -- wenn ich bis hierhin gelesen habe, bin ich bereit, dass
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   Nutzer mit Node.js an, so daß ein Link zur npmjs.org und ein
```suggestion
   Nutzer mit Node.js an, so dass ein Link zur npmjs.org und ein
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   Installationsbefehl ihnen die Reßourcen an die Hand gibt, um herauszufinden,
```suggestion
   Installationsbefehl ihnen die Ressourcen an die Hand gibt, um herauszufinden,
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   oben beßer aufgehoben sein; du wirst ein Modul wohl sehr schnell
```suggestion
   oben besser aufgehoben sein; du wirst ein Modul wohl sehr schnell
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   außchließen, wenn die Lizenz mit deiner Arbeit unkompatibel ist. Generell
```suggestion
   ausschließen, wenn die Lizenz mit deiner Arbeit unkompatibel ist. Generell
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   tendiere ich zu MIT/BSD/X11/ISC-Varianten. Falls du eine non-permißive
```suggestion
   tendiere ich zu MIT/BSD/X11/ISC-Varianten. Falls du eine non-permissive
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Nutzer von Modulen benutzen viele, und sie müßen sich viele Module anschauen.
```suggestion
Nutzer von Modulen benutzen viele, und sie müssen sich viele Module anschauen.
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Nachdem du Hunderte von Modulen betrachtet hast, wirst du bemerken, daß der
```suggestion
Nachdem du Hunderte von Modulen betrachtet hast, wirst du bemerken, dass der
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +2. das Vorhandensein bestimmter Schlüßelelemente
```suggestion
2. das Vorhandensein bestimmter Schlüsselelemente
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Du mußt nicht *dieses* Format nutzen, aber versuche konsistent zu sein, um
```suggestion
Du musst nicht *dieses* Format nutzen, aber versuche konsistent zu sein, um
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +intereßiert genug sind, um so weit unten im Dokument anzugelangen. Das Ende
```suggestion
interessiert genug sind, um so weit unten im Dokument anzugelangen. Das Ende
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +tieferen Kontext der Arbeit intereßiert sind (Hintergrund, Danksagungen,
```suggestion
tieferen Kontext der Arbeit interessiert sind (Hintergrund, Danksagungen,
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +> Code; überspring die ungewöhnlichen Fälle oder alles, daß nicht von den
```suggestion
> Code; überspring die ungewöhnlichen Fälle oder alles, dass nicht von den
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +> seine Erinnerung auffrischen können, ohne auf "Bild ab" drücken zu müßen.
```suggestion
> seine Erinnerung auffrischen können, ohne auf "Bild ab" drücken zu müssen.
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +> und nach tieferes Wißen erhalten.
```suggestion
> und nach tieferes Wissen erhalten.
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Fantastisch; die Reihenfolge dieser Schlüßelelemente sollte dadurch bestimmt
```suggestion
Fantastisch; die Reihenfolge dieser Schlüsselelemente sollte dadurch bestimmt
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +laßen, um zu entscheiden, ob es ihre Bedürfniße erfüllt oder nicht -- und
```suggestion
lassen, um zu entscheiden, ob es ihre Bedürfnisse erfüllt oder nicht -- und
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +zu laßen und die Arbeit soweit wie möglich für sich selbst sprechen zu laßen.
```suggestion
zu lassen und die Arbeit soweit wie möglich für sich selbst sprechen zu lassen.
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +beschreiben, so daß Modul-Höhlenforscher entweder deine Arbeit, sofern sie
```suggestion
beschreiben, so dass Modul-Höhlenforscher entweder deine Arbeit, sofern sie
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +paßt, benutzen, oder sich nach etwas anderem umsehen können.
```suggestion
passt, benutzen, oder sich nach etwas anderem umsehen können.
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Außer den Schlüßelpunkten dieses Artikels gibt es noch andere Praktiken, die
```suggestion
Außer den Schlüsselpunkten dieses Artikels gibt es noch andere Praktiken, die
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +README zu erhöhen und deßen Nützlichkeit für andere zu maximieren:
```suggestion
README zu erhöhen und dessen Nützlichkeit für andere zu maximieren:
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   sowie die Abstraktionen zu erklären, die jemand verstehen muß, um es zu
```suggestion
   sowie die Abstraktionen zu erklären, die jemand verstehen muss, um es zu
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   verlinke die Referenz, so daß Besucher einfach dein Module und die Ideen
```suggestion
   verlinke die Referenz, so dass Besucher einfach dein Module und die Ideen
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   ganze Arbeit beruht auf anderen Werken, also zahlt es sich aus, daß Nutzer
```suggestion
   ganze Arbeit beruht auf anderen Werken, also zahlt es sich aus, dass Nutzer
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   -- vielleicht als `example.js`. Es ist klaße, README code zu haben, den
```suggestion
   -- vielleicht als `example.js`. Es ist klasse, README code zu haben, den
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   [mißbraucht](https://github.com/angular/angular) werden. Sie können auch
```suggestion
   [missbraucht](https://github.com/angular/angular) werden. Sie können auch
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   E-Mail geschickt oder ein Ißue erstellt wird. Bedenke immer das Publikum
```suggestion
   E-Mail geschickt oder ein Issue erstellt wird. Bedenke immer das Publikum
```
:joy_cat:

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   der Daten in deiner README und frage dich selber, ob es einen Fluß für
```suggestion
   der Daten in deiner README und frage dich selber, ob es einen Fluss für
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   diese Daten gibt, die das gewünschte Publikum beßer erreicht.
```suggestion
   diese Daten gibt, die das gewünschte Publikum besser erreicht.
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   c. für `opts` Objekt-Parameter, alle akzeptierten Schlüßel-Wert-Paare
```suggestion
   c. für `opts` Objekt-Parameter, alle akzeptierten Schlüssel-Wert-Paare
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +      Dies kann aber auch ein starker Hinweis darauf sein, daß die Funktion zu
```suggestion
      Dies kann aber auch ein starker Hinweis darauf sein, dass die Funktion zu
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +      komplett entfernt werden muß
```suggestion
      komplett entfernt werden muss
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +      Ende deines Dokuments einfügen, so daß das erneute Verweisen von ihnen
```suggestion
      Ende deines Dokuments einfügen, so dass das erneute Verweisen von ihnen
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +      API-Formatierung laßen sich
```suggestion
      API-Formatierung lassen sich
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   [Node REPL seßion](https://github.com/noffle/bisecting-between#example) von
```suggestion
   [Node REPL session](https://github.com/noffle/bisecting-between#example) von
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   Funktionsaufrufen und -ergebnißen vielleicht den Gebrauch klarer ausdrücken
```suggestion
   Funktionsaufrufen und -ergebnissen vielleicht den Gebrauch klarer ausdrücken
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +9. Vergiß nicht, [Keywords](https://docs.npmjs.com/files/package.json#keywords)
```suggestion
9. Vergiss nicht, [Keywords](https://docs.npmjs.com/files/package.json#keywords)
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +10. Je mehr du dein API veränderst, desto mehr Arbeit mußt du darauf
```suggestion
10. Je mehr du dein API veränderst, desto mehr Arbeit musst du darauf
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +    daß du dein API klein halten und früh konkret definieren solltest.
```suggestion
    dass du dein API klein halten und früh konkret definieren solltest.
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +    ergibt, erstelle ein neues Modul, daß die Aufgabe erledigt. Das
```suggestion
    ergibt, erstelle ein neues Modul, dass die Aufgabe erledigt. Das
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +11. Schlußendlich, erinnere dich bitte, daß deine Versionskontroll-Repository
```suggestion
11. Schlussendlich, erinnere dich bitte, dass deine Versionskontroll-Repository
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +- https://github.com/feroß/bittorrent-dht
```suggestion
- https://github.com/feross/bittorrent-dht
```
:warning:

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +- [ ] Verläßt sich nicht auf Bilder, um kritische Informationen zu vermitteln
```suggestion
- [ ] Verlässt sich nicht auf Bilder, um kritische Informationen zu vermitteln
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +Der Abschnitt zu "README Tipps" floß allerdings mit Tipps über, so daß ich
```suggestion
Der Abschnitt zu "README Tipps" floss allerdings mit Tipps über, so dass ich
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +   Kleinbuchstaben sortieren, so daß sich die Nützlichkeit der Konvention
```suggestion
   Kleinbuchstaben sortieren, so dass sich die Nützlichkeit der Konvention
```

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +[@feroß](https://github.com/feroß) für die Ermunterung, die ich brauchte, um
```suggestion
[@feross](https://github.com/feross) für die Ermunterung, die ich brauchte, um
```
:warning:

2021-04-10 13:23 UTC, Ryuno-Ki commented on README-de-DE.md
> +[als ißue](https://github.com/noffle/art-of-readme/ißues)!
```suggestion
[als issue](https://github.com/noffle/art-of-readme/issues)!
```

2021-04-10 13:23 UTC, Ryuno-Ki requested changes
Search and Replace would have been too easy.

2021-04-10 13:24 UTC, Ryuno-Ki requested changes
ß passt noch nicht

2021-04-11 09:04 UTC, chnuessli commented on README-de-CH.md
> +Node.js hat ein "großes" Ökosystem: Es besteht im Wesentlichen aus einer
Ich verstehe echt nciht wann ein ß gemacht wird und wann eben nicht.

2021-04-11 09:05 UTC, chnuessli commented
So, i've resolved your suggestions.

2021-04-11 10:48 UTC, Ryuno-Ki commented on README-de-CH.md
> +Node.js hat ein "großes" Ökosystem: Es besteht im Wesentlichen aus einer
Ich nahm einfach an, dass es im Schweizer Deutsch kein ß gab.

2021-04-13 18:33 UTC, Ryuno-Ki commented
@randomC0der Could you lend another pair of eyes on this?

2021-04-13 21:57 UTC, randomC0der requested changes
My suggestions should be taken with a grain of salt because I am a true northerner. I'll look at it again after you applied the changes.

2021-04-13 21:57 UTC, randomC0der commented on README-de-CH.md
> +Interdependenz: niemand lebt wirklich am Fuße des Abhängigkeitsbaums.
```suggestion
Interdependenz: Niemand lebt wirklich am Fuße des Abhängigkeitsbaums.
```

2021-04-13 21:57 UTC, randomC0der commented on README-de-CH.md
> +Manchmal handelt es sich nur um einen Einzeiler: `"sortiert Nummern nach ihren
```suggestion
Manchmal handelt es sich nur um einen Einzeiler: `"Sortiert Nummern nach ihren
```

2021-04-13 21:57 UTC, randomC0der commented on README-de-CH.md
> +Darüberhinaus lässt sich Auffindbarkeit -- wie wir herausfinden werden --
```suggestion
Darüberhinaus lässt sich Auffindbarkeit -- wie wir später herausfinden werden --
```

2021-04-13 21:57 UTC, randomC0der commented on README-de-CH.md
> +die GitHub's sozialen Graphen verwendet, um Module zu finden, die deine Freunde
```suggestion
die GitHubs sozialen Graphen verwendet, um Module zu finden, die deine Freunde
```

2021-04-13 21:57 UTC, randomC0der commented on README-de-CH.md
> +ein sicherer Standard und der übliche Einstiegspunkt für neue Entwickler.
```suggestion
Ein sicherer Standard und der übliche Einstiegspunkt für neue Entwickler.
```

2021-04-13 21:57 UTC, randomC0der commented on README-de-CH.md
> +Das Fehlen einer README ist eine starke Warnsignal, aber auch eine lange
```suggestion
Das Fehlen einer README ist ein starkes Warnsignal, aber auch eine lange
```

2021-04-13 21:57 UTC, randomC0der commented on README-de-CH.md
> +   Fantastisch: es definiert AABB und was das Modul macht. Jetzt zum Abschätzen,
```suggestion
   Fantastisch: Es definiert AABB und was das Modul macht. Jetzt zum Abschätzen,
```

2021-04-13 21:57 UTC, randomC0der commented on README-de-CH.md
> +2. *Einzeiler* -- ein Einzeiler zur Beschreibung des Moduls kann nützlich sein,
```suggestion
2. *Einzeiler* -- Ein Einzeiler zur Beschreibung des Moduls kann nützlich sein,
```

2021-04-13 21:57 UTC, randomC0der commented on README-de-CH.md
> +Das klingt rau, stimmt's? Aber denk drüber nach: es ist nicht deine Aufgabe,
```suggestion
Das klingt rau, stimmt's? Aber denk drüber nach: Es ist nicht deine Aufgabe,
```

2021-04-13 21:57 UTC, randomC0der commented on README-de-CH.md
> +   e. verlinke spezielle Terminologie! In Markdown kannst du
```suggestion
   e. Verlinke spezielle Terminologie! In Markdown kannst du
```

2021-04-13 21:57 UTC, randomC0der commented on README-de-CH.md
> +   a. welche Parameter sind optional, sowie ihre Standardwerte
Wäre es nicht sinnvoller, wenn eine unsortierte Liste zu verwenden?

2021-04-13 21:57 UTC, randomC0der commented on README-de-CH.md
> +      finden
```suggestion
      finden.
```

2021-04-13 21:57 UTC, randomC0der commented on README-de-CH.md
> +      komplett entfernt werden muss
```suggestion
      komplett entfernt werden muss.
```

2021-04-13 21:57 UTC, randomC0der commented on README-de-CH.md
> +Dieses kleine Projekt begann damals im Main in Berlin bei der squantconf, wo
```suggestion
Dieses kleine Projekt begann damals im Mai in Berlin bei der squantconf, wo
```

2021-04-14 07:43 UTC, randomC0der commented on README-de-CH.md
> +## Für Ersteller, für Konsumierende
```suggestion
## Für Ersteller, für Nutzer
```
"Konsumierende" ist zwar die treffende Übersetzung, aber hört sich meiner Meinung nach etwas holprig an.

2021-04-14 07:43 UTC, randomC0der commented on README-de-CH.md
> +Dies ist ebenso für Konsumierende von Modulen geschrieben, da jeder Autor auch
```suggestion
Dies ist ebenso für Nutzer von Modulen geschrieben, da jeder Autor auch
```
s.o.

2021-04-16 06:30 UTC, chnuessli commented
All changes commited, thank you very much.

2021-04-16 17:40 UTC, randomC0der commented
Please restore all the ss and ß changes in de-DE.

2021-04-17 17:25 UTC, closed without merging